<#
.SYNOPSIS
    GitHub Profile Setup for HomeLab
.DESCRIPTION
    Sets up GitHub profile README with metrics, trophies, and stats.
    Creates workflows for automated profile updates.
    
.EXAMPLE
    .\setup-github-profile.ps1
    
.EXAMPLE
    .\setup-github-profile.ps1 -Username "your-github-username"
#>

[CmdletBinding()]
param(
    [string]$Username,
    [string]$OutputDir = ".",
    [switch]$CreateWorkflows
)

$ErrorActionPreference = "Stop"

# Colors
function Write-Step {
    param([string]$Message, [string]$Status = "INFO")
    $color = switch ($Status) {
        "SUCCESS" { "Green" }
        "WARN" { "Yellow" }
        "ERROR" { "Red" }
        "PHASE" { "Magenta" }
        default { "Cyan" }
    }
    $prefix = switch ($Status) {
        "SUCCESS" { "[OK] " }
        "WARN" { "[!] " }
        "ERROR" { "[X] " }
        "PHASE" { "`n>> " }
        default { "[i] " }
    }
    Write-Host "$prefix$Message" -ForegroundColor $color
}

# Banner
Write-Host ""
Write-Host "  ╔══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║           📊 GitHub Profile Setup                        ║" -ForegroundColor Cyan
Write-Host "  ╚══════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# Get username if not provided
if (-not $Username) {
    try {
        $gitConfig = git config --get user.name 2>$null
        if ($gitConfig) {
            Write-Host "  Detected Git user: $gitConfig" -ForegroundColor Gray
        }
    } catch {
        Write-Host "  Could not detect git username automatically" -ForegroundColor Gray
    }
    
    $Username = Read-Host "  Enter your GitHub username"
    if (-not $Username) {
        Write-Step "Username required" -Status ERROR
        exit 1
    }
}

Write-Step "Setting up profile for: $Username" -Status PHASE

# Create output directory
$profileDir = Join-Path $OutputDir $Username
if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

# ==============================================================================
# Create Profile README
# ==============================================================================

Write-Step "Creating profile README..." -Status PHASE

$readmeContent = @"
<!-- Profile README - Auto-generated by HomeLab -->
<!-- Last updated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss") -->

<div align="center">

# Hi there, I'm $Username 👋

<!-- Typing Animation -->
[![Typing SVG](https://readme-typing-svg.demolab.com?font=Fira+Code&pause=1000&color=00D9FF&center=true&vCenter=true&width=435&lines=Full+Stack+Developer;AI+%2B+Blockchain+Enthusiast;Open+Source+Contributor;Always+Learning)](https://git.io/typing-svg)

<!-- Profile Views -->
![Profile Views](https://komarev.com/ghpvc/?username=$Username&color=blueviolet&style=flat-square)

</div>

---

## 🛠️ Tech Stack

<div align="center">

![Python](https://img.shields.io/badge/Python-3776AB?style=for-the-badge&logo=python&logoColor=white)
![TypeScript](https://img.shields.io/badge/TypeScript-007ACC?style=for-the-badge&logo=typescript&logoColor=white)
![Solidity](https://img.shields.io/badge/Solidity-363636?style=for-the-badge&logo=solidity&logoColor=white)
![Docker](https://img.shields.io/badge/Docker-2496ED?style=for-the-badge&logo=docker&logoColor=white)
![React](https://img.shields.io/badge/React-61DAFB?style=for-the-badge&logo=react&logoColor=black)
![Node.js](https://img.shields.io/badge/Node.js-339933?style=for-the-badge&logo=node.js&logoColor=white)

</div>

---

## 📊 GitHub Stats

<div align="center">

<!-- GitHub Stats Card -->
<img src="https://github-readme-stats.vercel.app/api?username=$Username&show_icons=true&theme=tokyonight&hide_border=true&count_private=true" alt="GitHub Stats" />

<!-- Streak Stats -->
<img src="https://github-readme-streak-stats.herokuapp.com/?user=$Username&theme=tokyonight&hide_border=true" alt="GitHub Streak" />

<!-- Top Languages -->
<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=$Username&layout=compact&theme=tokyonight&hide_border=true&langs_count=8" alt="Top Languages" />

</div>

---

## 🏆 GitHub Trophies

<div align="center">

[![Trophies](https://github-profile-trophy.vercel.app/?username=$Username&theme=algolia&no-frame=true&no-bg=true&column=7)](https://github.com/ryo-ma/github-profile-trophy)

</div>

---

## 🐍 Contribution Graph

<div align="center">

![Snake animation](https://raw.githubusercontent.com/$Username/$Username/output/github-contribution-grid-snake-dark.svg)

</div>

---

## 📈 Activity Graph

<div align="center">

[![Activity Graph](https://github-readme-activity-graph.vercel.app/graph?username=$Username&theme=tokyo-night&hide_border=true)](https://github.com/ashutosh00710/github-readme-activity-graph)

</div>

---

## 🔗 Connect With Me

<div align="center">

[![GitHub](https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white)](https://github.com/$Username)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://linkedin.com/in/$Username)
[![Twitter](https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white)](https://twitter.com/$Username)

</div>

---

<div align="center">

### 💖 Thanks for visiting!

![Wave](https://raw.githubusercontent.com/mayhemantt/mayhemantt/Update/svg/Bottom.svg)

</div>
"@

$readmePath = Join-Path $profileDir "README.md"
$readmeContent | Out-File -FilePath $readmePath -Encoding UTF8 -Force
Write-Step "Created README.md" -Status SUCCESS

# ==============================================================================
# Create GitHub Actions Workflows
# ==============================================================================

if ($CreateWorkflows) {
    Write-Step "Creating GitHub Actions workflows..." -Status PHASE
    
    $workflowDir = Join-Path $profileDir ".github\workflows"
    if (-not (Test-Path $workflowDir)) {
        New-Item -ItemType Directory -Path $workflowDir -Force | Out-Null
    }
    
    # Snake animation workflow
    $snakeWorkflow = @"
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: `${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg
      
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: `${{ secrets.GITHUB_TOKEN }}
"@
    
    $snakeWorkflow | Out-File -FilePath (Join-Path $workflowDir "snake.yml") -Encoding UTF8 -Force
    Write-Step "Created snake.yml workflow" -Status SUCCESS
    
    # Metrics workflow
    $metricsWorkflow = @"
name: Profile Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Daily
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: `${{ secrets.METRICS_TOKEN }}
          user: `${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/New_York
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          
          plugin_calendar: yes
          plugin_calendar_limit: 1
"@
    
    $metricsWorkflow | Out-File -FilePath (Join-Path $workflowDir "metrics.yml") -Encoding UTF8 -Force
    Write-Step "Created metrics.yml workflow" -Status SUCCESS
}

# ==============================================================================
# Complete
# ==============================================================================

Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "  ║           ✅ Profile Setup Complete!                          ║" -ForegroundColor Green
Write-Host "  ╚═══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""

Write-Host "  Files created in: $profileDir" -ForegroundColor White
Write-Host ""
Write-Host "  NEXT STEPS:" -ForegroundColor Cyan
Write-Host "  ───────────" -ForegroundColor DarkGray
Write-Host "  1. Create a repository named '$Username' on GitHub" -ForegroundColor Gray
Write-Host "  2. Copy the files to your repository:" -ForegroundColor Gray
Write-Host "     cp -r $profileDir/* ~/your-profile-repo/" -ForegroundColor DarkGray
Write-Host "  3. Commit and push to GitHub" -ForegroundColor Gray
Write-Host ""

if ($CreateWorkflows) {
    Write-Host "  WORKFLOW SETUP:" -ForegroundColor Cyan
    Write-Host "  ────────────────" -ForegroundColor DarkGray
    Write-Host "  1. Go to repo Settings > Secrets > Actions" -ForegroundColor Gray
    Write-Host "  2. Add METRICS_TOKEN with a PAT (repo, read:user scopes)" -ForegroundColor Gray
    Write-Host "  3. Enable Actions in Settings > Actions > General" -ForegroundColor Gray
    Write-Host ""
}

Write-Host "  📚 Documentation: docs/GITHUB_PROFILE.md" -ForegroundColor Cyan
Write-Host ""
